DECLARE 
    input number;
BEGIN 
    input := &input;
    CASE input
        WHEN 1 THEN DBMS_OUTPUT.PUT_LINE('MONDAY');
        WHEN 2 THEN DBMS_OUTPUT.PUT_LINE('TUESDAY');
        WHEN 3 THEN DBMS_OUTPUT.PUT_LINE('WEDNESDAY');
        WHEN 4 THEN DBMS_OUTPUT.PUT_LINE('THURSDAY');
        WHEN 5 THEN DBMS_OUTPUT.PUT_LINE('FRIDAY');
        WHEN 6 THEN DBMS_OUTPUT.PUT_LINE('SATURDAY');
        WHEN 7 THEN DBMS_OUTPUT.PUT_LINE('SUNDAY');
        ELSE DBMS_OUTPUT.PUT_LINE('INVALID INPUT');
    END CASE;
END;
/